
jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'

#  error:
#    whitelabel:
#      enabled: false

server:
  port: 8081

spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/hale_db #change this to your database url
    url: jdbc:mysql://aws.connect.psdb.cloud:3306/hale_db #change this to your database url
    #password: Cotemar19 #change this to your database password 
    #username: GABRIEL #change this to your database username
    password: pscale_pw_3s4hYQmfj0N4U0xe17vPjv4LLcYC5GMZVdYDuBsi5l #change this to your database password 
    username: wpo202sgpn7f81vetb07 #change this to your database username
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart: 
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      add-mappings: false
  
 