
jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'

#  error:
#    whitelabel:
#      enabled: false

server:
  port: 8081

spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/hale_db #change this to your database url
    url: jdbc:sqlserver://187.188.105.90:1477;databaseName=AgoPlanogram #change this to your database url
    #password: Cotemar19 #change this to your database password 
    #username: GABRIEL #change this to your database username
    password: Ago0102!* #change this to your database password 
    username: UserLuisF #change this to your database username
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
  servlet:
    multipart: 
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      add-mappings: false
  
 